[theme]
primaryColor="#78a7c6"
backgroundColor="#fafafa"
secondaryBackgroundColor="#f86f17"
textColor="#2c2b2b"
font="sans serif"
#6d7e32
#Chagal
#78a7c6   1
#d7d1ae 1 3
#8bb822 3
#c94928
#13747d   2
#b3d579 2
#f86f17     3
#f2d724       4
